windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# make calculator floating and move it float right
windowrule{
    name = calculator
    match:class = org.gnome.Calculator
    move = monitor_w-450 80
    float = yes
}

#make audio player floating and move it to the center of the screen
windowrule{
    name = audio player
    match:class = org.gnome.Decibels
    move = center
    float = yes
    size = 480 260
}

#make file picker floating and move it to the center of the screen
windowrule {
    name = portal file dialogs
    match:class = ^xdg-desktop-portal-.*$
    center = yes
    size = 800 550
    float = yes
}

#make kdenlive splash screen floating and move to center
windowrule {
    name = kdenlive splash
    match:class = org.kde.kdenlive
    match:title = ^Kdenlive$
    float = yes
    center = yes
}

#make appmanager floating
windowrule{
  name = appmanager
  match:class = com.github.AppManager
  float = yes
  center = yes
}

#make kdeconnect floating
windowrule{
  name = kdeconnect
  match:class = org.kde.kdeconnect.app
  float = yes
  center = yes
  size = 600 460
}

#make qBittorrent floating
windowrule{
  name = qBittorrent
  match:class = org.qbittorrent.qBittorrent
  match:title = ^Preferences$
  float = yes
  center = yes
  size = 916 625
}

#make qBittorrent floating
windowrule{
  name = qBittorrent
  match:class = org.qbittorrent.qBittorrent
  match:title = ^qBittorrent v5.1.4$
  float = yes
  center = yes
  size = 1100 700
}

#make mpv floating
windowrule{
  name = mpv
  match:class = mpv
  float = yes
  center = yes
}
