UP add volume 5
DOWN add volume -5

+ add speed 0.1
- add speed -0.1
= set speed 1.0

b cycle audio
v cycle sub

o show-progress

< playlist-prev
> playlist-next

s screenshot

z add sub-delay -0.5
x add sub-delay 0.5
