osc=no
osd-level=0
save-position-on-quit

autofit-larger=1280x720
player-operation-mode=pseudo-gui

profile=high-quality
hwdec=auto-safe

volume-max=150

sub-auto=fuzzy
sub-font-size=36
sub-border-size=2
sub-shadow-offset=1
