include ~/.cache/ambxst/kitty.conf

# terminal bell
enable_audio_bell               no

# font
font_family                     JetBrainsMono Nerd Font 
font_size                       13.0
disable_ligatures               no


# cursor customization
cursor_shape                    block
cursor_blink_interval           0
cursor_stop_blinking_after      0
shell_integration               no-cursor
cursor_trail                    3

#tab bar
tab_bar_style                   separator
tab_bar_align                   center
tab_separator                   "|"
tab_bar_background              none
inactive_tab_background         #28283A 
inactive_tab_foreground         #666688
tab_title_template              " {title.rsplit('/', 1)[-1]} "


# scrollback
scrollback_lines                5000
wheel_scroll_multiplier         3.0

# mouse
mouse_hide_wait                 -1

# window layout
remember_window_size            no
initial_window_width            1300
initial_window_height           750
window_border_width             1.5pt
enabled_layouts                 tall
window_padding_width            2
window_margin_width             2
hide_window_decorations         yes
background_opacity              0.8

# scroll-bar
scrollbar_handle_opacity        0
scrollbar_track_opacity         0
scrollbar_track_hover_opacity   0

#misc
confirm_os_window_close         0
sync_to_monitor                 no

